# Generated by Django 5.2.1 on 2025-07-04 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_project', '0002_document_niveau_universite_delete_article_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='niveau',
        ),
        migrations.RemoveField(
            model_name='document',
            name='universite',
        ),
        migrations.AddField(
            model_name='document',
            name='matiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='python_project.matiere'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Niveau',
        ),
        migrations.DeleteModel(
            name='Universite',
        ),
    ]
