# Generated by Django 5.2.1 on 2025-11-29 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "python_project",
            "0003_remove_document_niveau_remove_document_universite_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="speciality",
            options={"verbose_name_plural": "specialities"},
        ),
        migrations.AlterField(
            model_name="document",
            name="matiere",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="python_project.matiere",
            ),
        ),
        migrations.AlterField(
            model_name="university",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="universities/"),
        ),
    ]
