# Generated by Django 5.2.1 on 2026-01-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "python_project",
            "0004_alter_speciality_options_alter_document_matiere_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="university",
            name="calendar",
            field=models.FileField(blank=True, null=True, upload_to="calendars/"),
        ),
    ]
