# Generated by Django 5.2.1 on 2026-01-17 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("python_project", "0005_university_calendar"),
    ]

    operations = [
        migrations.AddField(
            model_name="level",
            name="speciality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="levels",
                to="python_project.speciality",
            ),
        ),
    ]
