# Generated by Django 5.2.1 on 2026-01-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("python_project", "0006_level_speciality"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="level",
            name="speciality",
        ),
    ]
