# Generated by Django 5.2.1 on 2026-01-28 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("python_project", "0007_alert_remove_level_speciality"),
    ]

    operations = [
        migrations.AddField(
            model_name="matiere",
            name="level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matieres",
                to="python_project.level",
            ),
        ),
    ]
