# Generated by Django 5.2.1 on 2026-01-28 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("python_project", "0008_matiere_level"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alert",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="document",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="level",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="matiere",
            options={"ordering": ["semester__level__name", "semester__name", "name"]},
        ),
        migrations.AlterModelOptions(
            name="semester",
            options={"ordering": ["level__name", "name"]},
        ),
        migrations.AlterModelOptions(
            name="speciality",
            options={"ordering": ["name"], "verbose_name_plural": "specialities"},
        ),
        migrations.AlterModelOptions(
            name="university",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="document",
            name="matiere",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="python_project.matiere",
            ),
        ),
        migrations.AlterField(
            model_name="level",
            name="name",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="matiere",
            name="level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matieres",
                to="python_project.level",
            ),
        ),
        migrations.AlterField(
            model_name="matiere",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matieres",
                to="python_project.semester",
            ),
        ),
        migrations.AlterField(
            model_name="matiere",
            name="speciality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matieres",
                to="python_project.speciality",
            ),
        ),
        migrations.AlterField(
            model_name="semester",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="semesters",
                to="python_project.level",
            ),
        ),
        migrations.AlterField(
            model_name="speciality",
            name="university",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="specialities",
                to="python_project.university",
            ),
        ),
        migrations.AlterField(
            model_name="university",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="matiere",
            unique_together={("semester", "name", "speciality")},
        ),
        migrations.AlterUniqueTogether(
            name="semester",
            unique_together={("level", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="speciality",
            unique_together={("university", "name")},
        ),
    ]
